package com.clm.contactlistmanager.entity;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import jakarta.persistence.*;
import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
//Specifies the Contact is JPA entity
@Entity

@Table(name = "contacts")
public class Contact {
    // Indicates that this field is the primary key of the database table.
    @Id
    // Specifies that this primary key will be generated by the database
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // First name must not be empty or null
    @NotNull(message = "First name cannot be empty")
    // Sets a min of 1 and max of 100 chars for the first name
    @Size(min = 1, max = 100, message = "First name should be between 1 and 100 chars")
    // Specifies that this field will be mapped to a database column with the same name.
    @Column(name = "first_name", nullable = false)
    private String firstName;

    @NotNull(message = "Last name cannot be empty")
    @Size(min = 1, max = 100, message = "Last name should be between 1 and 100 chars")
    @Column(name = "last_name", nullable = false)
    private String lastName;

    @NotNull(message = "Phone number cannot be empty")
    @Size(min = 1, max = 10, message = "Phone number should be between 1 and 10 chars")
    @Column(name = "phone_number", nullable = false)
    private String phoneNumber;

    @NotNull(message = "Email cannot be empty")
    // Sets a min of 1 and max of 100 chars for the first name
    @Size(min = 1, max = 50, message = "Email should be between 1 and 50 chars")
    @Column(name = "email", nullable = false)
    private String email;

    @NotNull(message = "Address cannot be empty")
    // This sets a minimum of 1 and a maximum of 255 characters for the address
    @Size(min = 1, max = 150, message = "Address should be between 1 and 150 chars")
    @Column(name = "address", nullable = false)
    private String address;

    // Automatically record the timestamp when a Contact object is created and persisted
    @Temporal(TemporalType.TIMESTAMP)    // Specifies how a time or date field should be stored in the database
    @Column(name = "date_created", updatable = false)   // Prevents updates to the creation timestamp
    @org.hibernate.annotations.CreationTimestamp
    private Date dateCreated;


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Date getDateCreated() {
        return dateCreated;
    }

    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
}
