package com.clm.contactlistmanager;

import javax.persistence.*;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
//Specifies the Contact is JPA entity
@Entity

@Table(name = "contacts")
public class Contact {
    // Indicates that this field is the primary key of the database table.
    @Id
    // Specifies that this primary key will be generated by the database
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Specifies that this field will be mapped to a database column with the same name.
    @Column(name = "first_name", nullable = false)
    private String firstName;

    @Column(name = "last_name", nullable = false)
    private String lastName;

    @Column(name = "phone_number", nullable = false)
    private String phoneNumber;

    @Column(name = "email", nullable = false)
    private String email;

    @Column(name = "address", nullable = false)
    private String address;

    // Automatically record the timestamp when a Contact object is created and persisted
    @Temporal(TemporalType.TIMESTAMP)    // Specifies how a time or date field should be stored in the database
    @Column(name = "date_created", updatable = false)   // Prevents updates to the creation timestamp
    @org.hibernate.annotations.CreationTimestamp
    private Date dateCreated;

    // Add standard getters, setters and other methods here


}
